import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import {
    Bebas_Neue,
    Oswald,
    DM_Sans,
    Nunito_Sans,
} from "next/font/google";
import "@/app/globals.css";
import { AuthProvider } from "@/context/use-auth";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import Csrf from "@/components/backend/csrf";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { PodcastProvider } from "@/context/use-podcast";
import HomeNav from "@/components/layout/home-nav";
import StorySpotlight from "@/components/layout/home-spotlight";
import PlayBar from "@/components/player/play-bar";
import FullScreenPlayer from "@/components/player/full-screen-player";
import GlobalAudio from "@/components/player/global-audio";

// Fonts
const bebasNeue = Bebas_Neue({
    variable: "--font-bebas-neue",
    subsets: ["latin"],
    weight: "400",
});
const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ["latin"],
});
const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
});
const nunitoSans = Nunito_Sans({
    variable: "--font-nunito-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Bakha Bazar",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let firstPodcast = null;

    try {
        const res = await fetch(
            `${process.env.NEXT_PUBLIC_BACKEND}/api/story/?number=1`,
            { cache: "no-store" }
        );

        if (!res.ok) {
            throw new Error(`Failed to fetch initial story list: ${res.status}`);
        }

        const data = await res.json();

        if (!data || !Array.isArray(data) || data.length === 0) {
            throw new Error("No story data returned from API");
        }

        const spPodcast = await fetch(
            `${process.env.NEXT_PUBLIC_BACKEND}/api/story/?uuid=${data[0].uuid}`
        );

        if (!spPodcast.ok) {
            throw new Error(`Failed to fetch spotlight story: ${spPodcast.status}`);
        }

        firstPodcast = await spPodcast.json();
    } catch (error) {
        console.error("Error fetching initial podcast data:", error);
        // fallback: can use placeholder data or null
        firstPodcast = null;
    }

    return (
        <html lang="en">
            <head>
                <meta name="apple-mobile-web-app-title" content="BakhaBazar" />
            </head>
            <body
                className={`
                    ${bebasNeue.variable} 
                    ${oswald.variable} 
                    ${dmSans.variable} 
                    ${nunitoSans.variable} 
                    antialiased
                `}
            >
                <AuthProvider>
                    <SidebarProvider
                        className="h-screen w-full overflow-hidden lg:p-2"
                        defaultOpen={false}
                    >
                        <Csrf />
                        <AppSidebar className="py-5" />

                        <PodcastProvider initialPodcast={{ type: "story", ...firstPodcast }}>
                            <GlobalAudio />
                            <SidebarInset className="flex flex-col">
                                <HomeNav />
                                <div className="flex flex-col overflow-y-auto no-scroll gap-6 bg-secondary-background">
                                    <div id="home-main" className="grid grid-cols-1 lg:grid-cols-3">
                                        <div className="lg:col-span-2">{children}</div>
                                        <div className="hidden lg:col-span-1 lg:block min-w-[280px] lg:sticky lg:top-4 self-start">
                                            <StorySpotlight />
                                        </div>
                                    </div>
                                </div>
                                <PlayBar />
                                <FullScreenPlayer />
                            </SidebarInset>
                        </PodcastProvider>
                    </SidebarProvider>
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    );
}
