import type { Metadata } from "next"
import { Toaster } from "@/components/ui/sonner"
import {
    Bebas_Neue,
    Oswald,
    DM_Sans,
    Nunito_Sans,
} from "next/font/google"
import "@/app/globals.css"
import { AuthProvider } from "@/context/use-auth"

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import Csrf from "@/components/backend/csrf";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { PodcastProvider } from "@/context/use-podcast";
import HomeNav from "@/components/layout/home-nav";
import StorySpotlight from "@/components/layout/home-spotlight";
import PlayBar from "@/components/player/play-bar";

// Bebas Neue (good for big titles)
const bebasNeue = Bebas_Neue({
    variable: "--font-bebas-neue",
    subsets: ["latin"],
    weight: "400",
})
// Oswald (strong headings)
const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ["latin"],
})
// DM Sans (Spotify-like body text)
const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
})
// Nunito Sans (clean alternative body font)
const nunitoSans = Nunito_Sans({
    variable: "--font-nunito-sans",
    subsets: ["latin"],
})
export const metadata: Metadata = {
    title: "Bakha Bazar",
    description: "Generated by create next app",
}
export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode

}>) {
    const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND}/api/story/?number=1`, { cache: "no-store" })
    
    const data = await res.json()

    const spPodcast = await fetch(`${process.env.NEXT_PUBLIC_BACKEND}/api/story/?uuid=${data[0].uuid}`)

    const firstPodcast = spPodcast.ok ? await spPodcast.json() : null;

    return (
        <html lang="en">
            <head>
                <meta name="apple-mobile-web-app-title" content="BakhaBazar" />
            </head>
            <body
                className={`
                    ${bebasNeue.variable} 
                    ${oswald.variable} 
                    ${dmSans.variable} 
                    ${nunitoSans.variable} 
                    antialiased
                    `}
            >
                <AuthProvider>
                    <SidebarProvider
                        className="h-screen w-full overflow-hidden lg:p-2"
                        defaultOpen={false}
                    >
                        <Csrf />

                        {/* Sidebar */}
                        <AppSidebar className=" py-5" />

                        <PodcastProvider initialPodcast={{ type: "story", ...firstPodcast}}>
                            {/* Main content - Wrap with both providers */}
                            <SidebarInset className="flex flex-col">

                                {/* Fixed Navbar at top */}
                                <HomeNav />

                                {/* Scrollable content */}
                                <div className="flex flex-col overflow-y-auto no-scroll gap-6 bg-secondary-background">
                                    {/* Responsive main + spotlight layout */}
                                    <div id="home-main" className="grid grid-cols-1 lg:grid-cols-3">
                                        {/* Left column - ViewRenderer takes col-span-2 */}
                                        <div className="lg:col-span-2">
                                            {children}
                                        </div>

                                        {/* Right column (spotlight) */}
                                        <div className="hidden lg:col-span-1 lg:block min-w-[280px] lg:sticky lg:top-4 self-start">
                                            <StorySpotlight />
                                        </div>
                                    </div>
                                </div>

                                {/* Fixed PlayBar at bottom */}
                                <PlayBar />
                            </SidebarInset>

                        </PodcastProvider>
                    </SidebarProvider>
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    )
}